routes/web.php
<?php
// phpcs:disable
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserController@index');
Route::resource('/users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php
// phpcs:disable
namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;

class UserController extends Controller
{
    public function index()
    {
        $users = User::latest()->paginate();
        return view('welcome')
            ->with('users', $users);
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(UserRequest $request)
    {
        // dd($request->all());
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password),
        ]);
        return \redirect('/');
    }

    public function edit(User $user)
    {
        return view('users.edit')
            ->with('user', $user);
    }

    public function update(UserRequest $request, User $user)
    {
        $user->name = $request->name;
        $user->email = $request->email;
        
        if ($request->password) {
            $user->password = $request->password;
        }
        
        $user->save();
        return \redirect('/');
    }

    public function destroy(User $user)
    {
        $user->delete();
        return \redirect('/');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Crud Ejemplo</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
</head>
<body>
  @include('layouts.header')
  @yield('content')
</body>
</html>

resources/views/layouts/header.blade.php
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      soy un header
    </div>
  </div>
</div>

resources/views/users/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 my-5">
              @if (session('status'))
                <div class="alert alert-success" role="alert">
                  {{ session('status') }}
                </div>
              @endif
              <form action="{{ route('users.store') }}" method="post">
                <div class="form-group">
                  <label for="">
                    Name
                  </label>
                  <input
                    type="text"
                    name="name"
                    class="form-control"
                    value="{{ old('name') }}"
                    required
                  >
                </div>
                <div class="form-group">
                  <label for="">
                    Email
                  </label>
                  <input
                    type="email"
                    name="email"
                    class="form-control"
                    value="{{ old('email') }}"
                    required
                  >
                </div>
                <div class="form-group">
                  <label for="">
                    Password
                  </label>
                  <input
                    type="password"
                    name="password"
                    class="form-control"
                    value=""
                    required
                  >
                </div>
                <div class="form-group">
                  @csrf
                  {{-- @method('PUT') --}}
                  <input type="submit" value="Send" class="btn btn-sm btn-primary">
                  <a href="{{ route('users.index') }}" class="btn btn-secondary btn-sm">
                    Abort
                  </a>
                </div>
              </form>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 my-5">
              @if (session('status'))
                <div class="alert alert-success" role="alert">
                  {{ session('status') }}
                </div>
              @endif
              <form action="{{ route('users.update', $user) }}" method="post">
                <div class="form-group">
                  <label for="">
                    Name
                  </label>
                  <input
                    type="text"
                    name="name"
                    class="form-control"
                    value="{{ old('name', $user->name) }}"
                    required
                  >
                </div>
                <div class="form-group">
                  <label for="">
                    Email
                  </label>
                  <input
                    type="email"
                    name="email"
                    class="form-control"
                    value="{{ old('email', $user->email) }}"
                    required
                  >
                </div>
                <div class="form-group">
                  <label for="">
                    Password
                  </label>
                  <input
                    type="password"
                    name="password"
                    class="form-control"
                    value=""
                  >
                </div>
                <div class="form-group">
                  @csrf
                  @method('PUT')
                  <input type="submit" value="Send" class="btn btn-sm btn-primary">
                  <a href="{{ route('users.index') }}" class="btn btn-secondary btn-sm">
                    Abort
                  </a>
                </div>
              </form>
            </div>
        </div>
    </div>
@endsection